### ISSUE TITLE
Syncing Contacts Not Working on Docker, Locally, or via Website

### ISSUE THREAD

**Issue by Repsay** [guyzyl/whatsapp-contact-sync#100]
Hello,

I'm having an issue with the contact syncing feature of the `whatsapp-contact-sync` tool. When I try to sync my contacts, whether it's on Docker, locally, or through the whasync.com website, it doesn't seem to perform any actions and immediately reports that it's done.

Here are the steps I've taken:
1. I log into the tool successfully.
2. I attempt to sync my contacts.
3. The tool does nothing noticeable and immediately reports that the syncing process is done.

There are no error messages or any indications of what could be wrong. The login process works fine, so it seems to be specifically an issue with the syncing feature.

Could you please look into this? I'd appreciate any help or guidance.

Thank you.

**Comment by guyzyl** [comment]
Just to clarify, you're able to login to WhatsApp, then Google, you get to the sync screen and it does nothing and the progress bar is stuck?
Or does it stop functioning in a different stage.

**Comment by Repsay** [comment]
Thank you for your response.

To clarify, I am able to successfully log into the WhatsApp-Contact-Sync tool without any issues. After logging in, I proceed to the sync screen and initiate the syncing process. However, when I click on the sync button, the progress bar shows up briefly and immediately fills up, indicating that the syncing process is done. However, upon checking, it is evident that no contacts have actually been synced.

This behavior is consistent whether I use the tool on Docker, locally, or through the whasync.com website. The progress bar gives a false indication of completion, and there are no error messages or any other indications of what could be causing the issue.

I hope this provides more clarity regarding the issue I'm experiencing. If you have any further questions or suggestions, please let me know. I would greatly appreciate any help or guidance you can provide. Thank you.

**Comment by guyzyl** [comment]
I just tried it myself, and I'm experiencing the exact same problem. I'll look into it.

**Comment by guyzyl** [comment]
This is the bug: [#2312](https://github.com/pedroslopez/whatsapp-web.js/issues/2312)
That field is used in order to filter out contacts that are on the users WhatsApp but are not saved as a contact.
It is possible to make everything run even without the filtering, but the way it is done right now causes it to be too slow.
There's already an [open PR](https://github.com/pedroslopez/whatsapp-web.js/pull/2325) to fix this, I'll give it a day and if it's not merged I'll work on a fix on my side.

**Comment by guyzyl** [comment]
@alechkos thanks for fixing the issue! It really did solve this problem :)
@Repsay let me know if it still isn't fixed for you.
