### ISSUE TITLE
Docker Build Fails due to TypeScript Error in web/src/main.ts

### ISSUE THREAD

**Issue by Repsay** [guyzyl/whatsapp-contact-sync#101]
Hello,

I encountered an issue while trying to build the Docker image for the `whatsapp-contact-sync` project. The build process fails during the `npm run build` step for the web-build with a TypeScript error.

The error message is as follows:

```
src/main.ts(68,41): error TS2345: Argument of type '{ pageTrackerTemplate(to: RouteLocationNormalized): { page_title: string; page_path: string; }; config: { id: string; }; }' is not assignable to parameter of type 'PluginOptions'.
Types of property 'pageTrackerTemplate' are incompatible.
Type '(to: RouteLocationNormalized) => { page_title: string; page_path: string; }' is not assignable to type '() => PageView'. 
```

It appears there's a type mismatch between the `pageTrackerTemplate` function and the `PluginOptions` type. The `pageTrackerTemplate` function seems to be expecting no arguments and a return type of `PageView`, but the provided function takes a `RouteLocationNormalized` argument and returns an object with `page_title` and `page_path`.

**Comment by guyzyl** [comment]
Thanks for fixing it!
