### ISSUE TITLE
It doesn't seem to work anymore

### ISSUE THREAD

**Issue by joaopna** [guyzyl/whatsapp-contact-sync#116]
I downloaded the code, ran the docker commands, loaded the page, scanned the QR Code and WhatsApp recognized and connected to another session successfully. However, the page keeps showing the QR Code, as if I had not connected yet, for over 5 minutes.

Am I supposed to wait longer? I don't see any error on the console log that might indicate any problem. Not sure if the .env credentials are correct, but there was no warning pointing to this problem.

The whasync.com demo website also seems to be hanging on the QR code

**Comment by guyzyl** [comment]
That's definitely not how it should act, the wait should be about 10 seconds.
I will check it out once I'm in front of a computer.

Thanks for reporting this!

**Comment by guyzyl** [comment]
I was able to replicate this, working on a fix.

**Comment by guyzyl** [comment]
This was the [issue](https://github.com/pedroslopez/whatsapp-web.js/issues/2433) that caused the service to stopped working (but also my fault for upgrading to the latest version without testing first).
It should now be fixed, let me know if your experience is different.
