### ISSUE TITLE
Limited number of contacts?

### ISSUE THREAD

**Issue by joaopna** [guyzyl/whatsapp-contact-sync#119]
I can only sync ~52 of my contacts pictures, even though I have hundreds. Is this an app ou Google API limitation? Any way to overcome?

**Comment by guyzyl** [comment]
There shouldn't any such limitation.
What do you experience when only 52 contacts are synced, does the progress bar get to 100%, or does the syncing "freeze"?

**Comment by joaopna** [comment]
The progress bar get to 100%.

**Comment by joaopna** [comment]
I think I know what the problem is. Some years ago here in Brazil, all cell phone numbers were added an extra '9' (area code + 8 numbers were not enough anymore). I'll check if the problem is actually this and if positive send a PR with a fix.

**Comment by joaopna** [comment]
Yep, that was the problem. I'm sending a PR with a fix for Brazillian numbers.
