### ISSUE TITLE
[feature request] Exclude specific Whatsapp contacts when uploading photos?

### ISSUE THREAD

**Issue by bigplayer-ai** [guyzyl/whatsapp-contact-sync#122]

**Comment by guyzyl** [comment]
Relates to #37, will require sending all contacts to the frontend to allow user selection of contacts.

For now, you can add a photo to the contacts you don't want synced, and sync everything with "overwrite pictures" option disabled.

**Comment by guyzyl** [comment]
Duplicates #37
