### ISSUE TITLE
404 when opening link

### ISSUE THREAD

**Issue by filippossio** [guyzyl/whatsapp-contact-sync#123]

**Comment by filippossio** [comment]
[whasync.com](https://github.com/guyzyl/whatsapp-contact-sync/blob/main/whasync.com)

**Comment by guyzyl** [comment]
Where did you copy paste this link from?
It is not working properly because it's looking for a file called `whasync.com` on this GitHub repo instead of pointing to the actual domain https://whasync.com

**Comment by guyzyl** [comment]
@filippossio thanks for opening the issue, and @3ternal thanks for pointing out its location!
It should be fixed now, let me know if the issue still persists.
