### ISSUE TITLE
Connecting whatsapp

### ISSUE THREAD

**Issue by emrahengin** [guyzyl/whatsapp-contact-sync#161]
![image](https://github.com/guyzyl/whatsapp-contact-sync/assets/169889097/cda1199f-3887-4827-a7c6-879a1f9db809)

**Comment by guyzyl** [comment]
Did this happen on whasync.com or when running the project locally?

**Comment by 233mhz** [comment]
Same issue
![Captura](https://github.com/guyzyl/whatsapp-contact-sync/assets/18459218/69d81e23-a303-4eec-a300-e63bc6567999)

**Comment by emrahengin** [comment]
it happened on whasync.com

**Comment by guyzyl** [comment]
When it didn't load, for how long did you wait?
Also, did you try refreshing the page?
(The QR can take ~15 seconds to load in some cases)

Can you please try to load it again, and if it doesn't work note down the time (and timezone) of when the issue occurred? That way I can try to find the issue in your specific session.

**Comment by Borkjev** [comment]
Same issue here

The selfhosted docker image crashes soon after the 'authorizing' hang.

I then bought you a coffee and tried in your hosted version.
I tried around 14:51 (UTC+2)

**Comment by guyzyl** [comment]
Ok, I'll check it out during the weekend.

**Comment by seemebreakthis** [comment]
A little different here.  Hosting locally, I am getting this.  No QR code is displayed.

![image](https://github.com/guyzyl/whatsapp-contact-sync/assets/5940900/d7becc9a-aff8-4667-b58e-cfc606c86954)

It used to work last time I tried, maybe 3 month ago.  I have re-cloned and re-build but still like this.

**Comment by guyzyl** [comment]
I just tried loading the QR by myself (both on whasync.com and locally), both of them worked without any issue.

I did go a bit into bugs I saw in the backend server, it seems that some things have changed with WhatsApp web API causing it not to work all of the time.
In any case, I merged the changes and they should be up in [whasync.com](whasync.com) within 15 minutes.

Can one of you confirm the change fixed the issue for you?
If #162 didn't fix it, there's also [this approach](https://github.com/pedroslopez/whatsapp-web.js/pull/2816) I can try out.

**Comment by Borkjev** [comment]
It's hanging on WhatsApp Authorizing for over 2 minutes again.
Tested now at 09:04 (UTC+2)

**Comment by guyzyl** [comment]
@Borkjev I was able to find the logs + replicate the issue.
The error logs I'm seeing are the same ones as yesterday, apparently #162 didn't do the trick.
I'll work on a different fix.

**Comment by guyzyl** [comment]
Alright, just merged #164 which fixed the issue locally for me.
Can someone confirm it's not only me? (should be up in [whasync.com](whasync.com) in < 15 mins)

**Comment by seemebreakthis** [comment]
Can confirm it is working for me.  Hosting locally.

**Comment by Borkjev** [comment]
Seems to work on whasync.com too.

**Comment by guyzyl** [comment]
Awesome, glad to hear

**Comment by 233mhz** [comment]
> Alright, just merged #164 which fixed the issue locally for me. Can someone confirm it's not only me? (should be up in [whasync.com](whasync.com) in < 15 mins)

14:02h (UTC +1 - From Spain)

I link the device with the QR but it does not continue.
It does not appear as an active session

**Comment by emrahengin** [comment]
Solved for me (on web)

**Comment by guyzyl** [comment]
> > Alright, just merged #164 which fixed the issue locally for me. Can someone confirm it's not only me? (should be up in [whasync.com](whasync.com) in < 15 mins)
> 
> 14:02h (UTC +1 - From Spain)
> 
> I link the device with the QR but it does not continue. It does not appear as an active session

I checked the backend, there are no errors at all + tested it myself and it seems to be working.
For how long did you wait after scanning? Because it can take some time.

**Comment by 233mhz** [comment]
> > > Alright, just merged #164 which fixed the issue locally for me. Can someone confirm it's not only me? (should be up in [whasync.com](whasync.com) in < 15 mins)
> > 
> > 
> > 14:02h (UTC +1 - From Spain)
> > I link the device with the QR but it does not continue. It does not appear as an active session
> 
> I checked the backend, there are no errors at all + tested it myself and it seems to be working. For how long did you wait after scanning? Because it can take some time.

More than 25 min

**Comment by guyzyl** [comment]
There were no errors at all in the past 24 hours (when I checked)
