### ISSUE TITLE
Greyed out "get started" button

### ISSUE THREAD

**Issue by theoware** [guyzyl/whatsapp-contact-sync#165]
Hey,

using the Dockerfile I'm only able to get to the landing page. I'm pretty sure, I've set the variables right. I hope, you are able to help me.

Logs:
```
[+] Building 1.1s (29/29) FINISHED docker:default
 => [internal] load build definition from Dockerfile 
 => => transferring dockerfile: 1.58kB 
 => [internal] load metadata for docker.io/library/node:21-alpine0.9s
 => [internal] load .dockerignore
 => => transferring context: 160B
 => [internal] load build context
 => => transferring context: 378.60kB
 => [server-build1/10] FROM docker.io/library/node:21-alpine@sha256:db8772d9f5796ac4e8c47508038c413ea1478da010568a2e48672f19a8b80cd2 
 => CACHED [stage-2 2/9] WORKDIR /app/server 
 => CACHED [stage-2 3/9] RUN apk update && apk add --no-cache nss udev ttf-freefont chromium nginx && rm -rf /var/cache/apk/* /tmp/* 
 => CACHED [stage-2 4/9] COPY ./assets/nginx.conf /etc/nginx/nginx.conf
 => CACHED [stage-2 5/9] COPY ./assets/entrypoint.sh . 
 => CACHED [stage-2 6/9] RUN chmod 755 entrypoint.sh 
 => CACHED [web-build 2/7] WORKDIR /app/web
 => CACHED [web-build 3/7] COPY [web/package.json, web/package-lock.json*, ./] 
 => CACHED [web-build 4/7] RUN npm install 
 => CACHED [web-build 5/7] COPY ./interfaces /app/interfaces 
 => CACHED [web-build 6/7] COPY ./web .
 => CACHED [web-build 7/7] RUN npm run build 
 => CACHED [stage-2 7/9] COPY --from=web-build /app/web/dist /var/www/html 
 => CACHED [server-build2/10] WORKDIR /app/server
 => CACHED [server-build3/10] COPY [server/package.json, server/package-lock.json*, ./]
 => CACHED [server-build4/10] RUN npm install
 => CACHED [server-build5/10] COPY ./interfaces /app/interfaces
 => CACHED [server-build6/10] COPY ./server .
 => CACHED [server-build7/10] RUN npm run build
 => CACHED [server-build8/10] RUN npm prune --production 
 => CACHED [server-build9/10] RUN apk update && apk add curl && curl -sf https://gobinaries.com/tj/node-prune | sh 
 => CACHED [server-build 10/10] RUN mv node_modules/googleapis/build/src/apis/docs ./docs && node-prune --exclude "**/googleapis/**/docs/*.js" && mv ./docs node_modules/googleapis/build/src/apis/docs
 => CACHED [stage-2 8/9] COPY --from=server-build /app/server/node_modules ./node_modules
 => CACHED [stage-2 9/9] COPY --from=server-build /app/server/build ./build
 => exporting to image 
 => => exporting layers
 => => writing image sha256:beb8fae821c8a5711ea0255f1b40c81c4cfb1b3440533abd8e5ee0b6918fddb4 
 => => naming to docker.io/library/whasync 

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
(node:7) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Listening on port 8080
Starting Nginx server
192.168.178.129 - - [22/May/2024:15:06:15 +0000] "GET / HTTP/1.1" 200 325 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0"
192.168.178.129 - - [22/May/2024:15:06:15 +0000] "GET /assets/index-Vs-X_rTS.js HTTP/1.1" 200 95513 "http://192.168.178.129/" "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0"
192.168.178.129 - - [22/May/2024:15:06:15 +0000] "GET /assets/index-PJwjaxPH.css HTTP/1.1" 200 55301 "http://192.168.178.129/" "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0"
192.168.178.129 - - [22/May/2024:15:06:15 +0000] "GET /logo.png HTTP/1.1" 200 574897 "http://192.168.178.129/" "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0"
192.168.178.129 - - [22/May/2024:15:06:15 +0000] "GET /assets/Home-MAK3bWtK.js HTTP/1.1" 200 1403 "http://192.168.178.129/assets/index-Vs-X_rTS.js" "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0"
2024/05/22 15:06:15 [error] 42#42: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.178.129, server: _, request: "GET /api/ HTTP/1.1", upstream: "http://127.0.0.1:8080/", host: "192.168.178.129", referrer: "http://192.168.178.129/"
192.168.178.129 - - [22/May/2024:15:06:15 +0000] "GET /api/ HTTP/1.1" 502 157 "http://192.168.178.129/" "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0"
2024/05/22 15:06:15 [error] 42#42: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.178.129, server: _, request: "GET /api/status HTTP/1.1", upstream: "http://127.0.0.1:8080/status", host: "192.168.178.129", referrer: "http://192.168.178.129/"
192.168.178.129 - - [22/May/2024:15:06:15 +0000] "GET /api/status HTTP/1.1" 502 157 "http://192.168.178.129/" "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0"
2024/05/22 15:06:15 [error] 44#44: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.178.129, server: _, request: "GET /api/ws HTTP/1.1", upstream: "http://127.0.0.1:8080/ws", host: "192.168.178.129"
192.168.178.129 - - [22/May/2024:15:06:15 +0000] "GET /api/ws HTTP/1.1" 502 157 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0"
```

Screenshot of webpage:
![grafik](https://github.com/guyzyl/whatsapp-contact-sync/assets/59124958/ebb03d69-2305-4dfa-aafe-abadc8912ebb)

**Comment by guyzyl** [comment]
What command line did you use to run the container + do you see any errors in the dev console?

**Comment by theoware** [comment]
Hey, I used the following command:

```
sudo docker build -t whasync .
sudo docker run --rm -it -p 80:80 whasync
```

What do you mean by dev console? The logs I sent above are the whole output of these two commands

**Comment by guyzyl** [comment]
In chrome press F12 on your keyboard to open the dev console, you should see the frontend's errors there

**Comment by theoware** [comment]
Here you go:
```
Some cookies are misusing the recommended “SameSite“ attribute 4
The resource at “<URL>” was blocked because content blocking is enabled. 2
Firefox can’t establish a connection to the server at ws://192.168.178.156/api/ws. index-Vs-X_rTS.js:21:30232
WS error - [object Event] index-Vs-X_rTS.js:21:30333
Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Partitioned cookie or storage access was provided to “https://ghbtns.com/github-btn.html?user=guyzyl&repo=whatsapp-contact-sync&type=star&count=true&size=large” because it is loaded in the third-party context and dynamic state partitioning is enabled.
```

**Comment by guyzyl** [comment]
Everything seems OK from the frontend perspective.
It seems that for some reason the backend is up (`Listening on port 8080`), but fails to respond to any of the requests it receives (`failed (111: Connection refused) while connecting to upstream`).

The thing is that the Docker image does work, it's what's powering [whasync.com](whasync.com) + I tried building it myself and running locally when you opened the issue.

My guess would be that it's a configuration problem of the backend.
Have you configured all of the ENV vars as mentioned in [README.md](https://github.com/guyzyl/whatsapp-contact-sync/blob/main/README.md)?
If you're sure you have, I'll try to think of another way to test my theory (remotely).

**Comment by theoware** [comment]
It's really weird. I've tried using older versions, setting network to host, also allowing port 8080, seperating web and backend. I also tried using it on a different computer.  Not only that, but I've also tried running it without docker using npm, that worked.
Before, it also worked on my pc. So I think it's some sort of update breaking the program.

**Comment by guyzyl** [comment]
Does the latest version (`main` branch) work for you using `npm`?

It's hard for me to pinpoint where things are going wrong on your machine remotely, so I'm trying to ask guiding questions in the hopes that you'll find something that causes it all to break.

**Comment by theoware** [comment]
Just tested and I can confirm it works using npm

**Comment by guyzyl** [comment]
So it defiantly has something to do with the container itself, but it does work for me meaning it has to do something with you environment.

Have you modified any of the files? Are there any local changes you have that are not on the `main` branch of the repo?

**Comment by theoware** [comment]
Apart from the env and google auth thing, I haven't changed anything.

Just now, I've also tried running on a fresh clone of the repo. Still the same result

**Comment by guyzyl** [comment]
Can you upload the container you built to dockerhub? I'll try to check it out myself.

**Comment by theoware** [comment]
Sure, thanks!
https://hub.docker.com/r/theoware/whasync/tags

**Comment by mryusufcan** [comment]
i'm having the same problem. Can you help me, please?
![Ekran görüntüsü 2024-08-19 210129](https://github.com/user-attachments/assets/42189089-11b6-4c03-b9f0-5c3165cb2b67)
![Ekran görüntüsü 2024-08-19 210528](https://github.com/user-attachments/assets/0036b5c7-939a-43bd-9228-a23490e12c67)
![Ekran görüntüsü 2024-08-19 210546](https://github.com/user-attachments/assets/f876a7a6-9f04-4d95-bbff-e8463e41d751)

**Comment by guyzyl** [comment]
@mryusufcan do you have the backend log? It seems the frontend is failing to connect to the websocket server of the backend.

**Comment by mryusufcan** [comment]
> @mryusufcan arka uç günlüğünüz var mı? Görünüşe göre ön uç, arka ucun websocket sunucusuna bağlanamıyor.

i think I need to share the docker log part. 

2024-08-20 18:17:52 (node:7) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
2024-08-20 18:17:52 (Use `node --trace-deprecation ...` to show where the warning was created)
2024-08-20 18:17:52 Listening on port 8080
2024-08-20 18:17:52 Starting Nginx server
2024-08-20 18:17:53 172.17.0.1 - - [20/Aug/2024:15:17:53 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0"
2024-08-20 18:17:53 172.17.0.1 - - [20/Aug/2024:15:17:53 +0000] "GET /assets/index-PJwjaxPH.css HTTP/1.1" 304 0 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0"
2024-08-20 18:17:53 172.17.0.1 - - [20/Aug/2024:15:17:53 +0000] "GET /assets/index-3D9aj0At.js HTTP/1.1" 304 0 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0"
2024-08-20 18:17:53 172.17.0.1 - - [20/Aug/2024:15:17:53 +0000] "GET /assets/Home-bdKD6MRW.js HTTP/1.1" 304 0 "http://localhost/assets/index-3D9aj0At.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0"
2024-08-20 18:17:53 172.17.0.1 - - [20/Aug/2024:15:17:53 +0000] "GET /logo.png HTTP/1.1" 304 0 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0"
2024-08-20 18:17:53 2024/08/20 15:17:53 [error] 62#62: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: _, request: "GET /api/ HTTP/1.1", upstream: "http://127.0.0.1:8080/", host: "localhost", referrer: "http://localhost/"
2024-08-20 18:17:53 172.17.0.1 - - [20/Aug/2024:15:17:53 +0000] "GET /api/ HTTP/1.1" 502 157 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0"
2024-08-20 18:17:53 2024/08/20 15:17:53 [error] 64#64: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: _, request: "GET /api/ws HTTP/1.1", upstream: "http://127.0.0.1:8080/ws", host: "localhost"
2024-08-20 18:17:53 172.17.0.1 - - [20/Aug/2024:15:17:53 +0000] "GET /api/ws HTTP/1.1" 502 157 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0"
2024-08-20 18:17:53 2024/08/20 15:17:53 [error] 62#62: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: _, request: "GET /api/status HTTP/1.1", upstream: "http://127.0.0.1:8080/status", host: "localhost", referrer: "http://localhost/"
2024-08-20 18:17:53 172.17.0.1 - - [20/Aug/2024:15:17:53 +0000] "GET /api/status HTTP/1.1" 502 157 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0"
2024-08-20 18:17:53 172.17.0.1 - - [20/Aug/2024:15:17:53 +0000] "GET /favicon.ico HTTP/1.1" 200 15406 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0"

**Comment by snqyz** [comment]
also facing issues both with the Docker image and npm approach (npm output below):

19:18:09 [vite] http proxy error at /:
AggregateError [ECONNREFUSED]:
    at internalConnectMultiple (node:net:1118:18)
    at afterConnectMultiple (node:net:1685:7)
19:18:09 [vite] http proxy error at /status:
AggregateError [ECONNREFUSED]:
    at internalConnectMultiple (node:net:1118:18)
    at afterConnectMultiple (node:net:1685:7)
19:18:09 [vite] ws proxy error:
AggregateError [ECONNREFUSED]:
    at internalConnectMultiple (node:net:1118:18)
    at afterConnectMultiple (node:net:1685:7)

**Comment by guyzyl** [comment]
@mryusufcan glad to hear! Can you write your solution here so the next people to run into the issue will be able to solve it as well?

**Comment by memehammad** [comment]
> > @mryusufcan arka uç günlüğünüz var mı? Görünüşe göre ön uç, arka ucun websocket sunucusuna bağlanamıyor.
> 
> i solved the problem somehow with chatgpt. thanks

lmaooo how about you tell us how you did it? I'm having the same issue.

**Comment by guyzyl** [comment]
@memehammad I’ve pushed a fix for this yesterday, you can follow the guide in the README on how to build the image.
If the you still experience the issue on the new build please let me know.
