### ISSUE TITLE
How to run local?

### ISSUE THREAD

**Issue by xstocler** [guyzyl/whatsapp-contact-sync#176]
Hello friends,
I tested the tool yesterday (of course I made the contribution).
I liked it and would like to know how to run it on my machine.

Which district do you recommend?
Centos/Debian?

Any step-by-step instructions on how to run it?

**Comment by guyzyl** [comment]
Hello, glad you liked it :)
You can use Docker to run it locally on any OS, you don't necessary need a linux machine for that.
Check out the [README.md](https://github.com/guyzyl/whatsapp-contact-sync?tab=readme-ov-file#whatsapp-contact-sync) for instructions.
If something isn't clear there or you're running into issues, feel free to re-open this issue and I'll help you out as best as I can.
