### ISSUE TITLE
On whasync.com sync stops after a few contacts

### ISSUE THREAD

**Issue by AIIucard** [guyzyl/whatsapp-contact-sync#181]
I started the sync via https://whasync.com/ and it stopped after 14 contacts were synced. There is no visual feedback on what happened and whether it will continue. I waited for 5 minutes and nothing happened. I also restarted the sync but the same happened again and again. I can confirm that the displayed contacts are synced to my Google account but that's it.
![image](https://github.com/user-attachments/assets/61b2f159-b0f2-46c7-b9f1-4799e0dd6e02)

**Comment by AIIucard** [comment]
After 5 or more restarts, it finally synced all available contacts. I didn't use "Overwrite image" this time. Maybe this helps to fix the bug. I suggest you add a visual indication of whether the app is working or stopped working...

Nevertheless, great work and it saved me a lot of time. I will definitely use it again 😊

**Comment by guyzyl** [comment]
Sorry that it took you 5 tries to get it to fully work, you can see an explanation of why that is [here](https://github.com/guyzyl/whatsapp-contact-sync/issues/179#issuecomment-2284691067) (FYI, it's not related to the "overwrite" toggle).
In regard to adding the visual indication if the app is working or not, that's a really good idea and I've opened issue #182 for it.

Glad you liked the app :)

**Comment by AIIucard** [comment]
Thank you very much for the info. I think you should also add a note that hints at the problems with whatsapp-web.js and that it's recommended to try again after a few minutes in case the import has failed.
