### ISSUE TITLE
Access blocked: Authorization Error

### ISSUE THREAD

**Issue by abuudarda** [guyzyl/whatsapp-contact-sync#193]
Running local. Getting this issue when trying to sign in with google.

Storagerelay URI is not allowed for 'NATIVE_DESKTOP' client type.
If you are a developer of whatsync, see [error details](https://accounts.google.com/).
Error 400: invalid_request

**Comment by guyzyl** [comment]
@abuudarda this is an issue with how you setup your Google auth app, you can see answers on how to resolve it [here on StackOverflow](https://stackoverflow.com/questions/40194824/google-sign-in-storagerelay-uri-is-not-allowed-for-39native39-client-type).

**Comment by abuudarda** [comment]
Really sorry. It was a rookie mistake from my side. but now I am getting this message in the same screen

Access blocked: This app’s request is invalid
 You can’t sign in because this app sent an invalid request. You can try again later, or contact the developer about this issue. [Learn more about this error](https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow#authorization-errors-origin-mismatch)
If you are a developer of this app, see [error details](https://accounts.google.com/).
Error 400: redirect_uri_mismatch

Do I need to add any Authorized JavaScript origins uri ?

**Comment by guyzyl** [comment]
Yes, you need to add your URI to Google otherwise you get the error you received here.
