### ISSUE TITLE
Unable run with docker desktop windows 11

### ISSUE THREAD

**Issue by sujoy-khan** [guyzyl/whatsapp-contact-sync#200]
I am new to docker desktop and outside app developing things. Anyone can help me to run step by step??

**Comment by guyzyl** [comment]
You can take a look at the Docker [quick start guide](https://docker-curriculum.com/#getting-started) to get started with Docker.
After that there are instructions in the [README.md](https://github.com/guyzyl/whatsapp-contact-sync/tree/main/README.md) file on how run whasync locally, but I will warn you that it takes some effort and probably isn't the easiest for beginners.

Alternatively, you can use [whasync.com](whasync.com) which is a hosted version of the repo and will cost you 1$ to use for a month.
