### ISSUE TITLE
QR code does not show

### ISSUE THREAD

**Issue by irabeamte2** [guyzyl/whatsapp-contact-sync#23]

**Comment by guyzyl** [comment]
Can you provide more details? Was this on the website or self hosted? Do you see any errors in the console?
In any case, I think this relates to #22 .

**Comment by irabeamte2** [comment]
when I go to https://whasync.com/ i click on get started and are redirected to https://whasync.com/whatsapp. where te QR could should pop up i get a loading screen. QR code never shows.

![2022-12-06 21_47_53-WhatsApp Contact Sync](https://user-images.githubusercontent.com/45318057/206019776-e33ceb3f-66ee-4ac3-92b5-ea422abe6390.png)

**Comment by guyzyl** [comment]
Can you check if #24 solved you issue?

**Comment by guyzyl** [comment]
I changed the GCP Run instance type, and the QR seems to be showing now.
@irabeamte2 does the issue still persist for you?

**Comment by irabeamte2** [comment]
I'm able to scan the QR code now and the sync works great. thanks!

**Comment by guyzyl** [comment]
Glad to hear :)
