### ISSUE TITLE
Just a comment

### ISSUE THREAD

**Issue by choco-latin** [guyzyl/whatsapp-contact-sync#34]
First of all thanks for your work, it works very well!

Just a few comments maybe :
* in terms of safety maybe you could add a paragraph in your README explaining how giving your app the required access does not mean you are going to steal some data. I am saying this thinking about "my parents" or anybody wanting to use this without any prior knowledge of what's going on
* still in terms of rights given, at the end of the process I had to go on my whatsapp parameters and google account parameters to revoke access to the app. I think that it would be nice that, at the end of the process, the webpage propose a couple of buttons to revoke the access (should be optional in case people want to regularly update their pictures)(I have no idea if this is technically possible). 
* A last comment : Before the sync there is an option to overwrite existing pictures. I think that I would have liked to decide this picture by picture!

**Comment by guyzyl** [comment]
Thanks for the kind words!
All 3 suggestions sound like great ideas. At one point I did plan on doing bullet 2 in the list, but it was too much effort for me at that time.
Can you please create a separate issue for each of the points you listed? Also, if you'd like to take a crack at them that would be very helpful :)

**Comment by guyzyl** [comment]
@choco-latin thanks!
