### ISSUE TITLE
[Bug Report] Whatsapp contact sync does not work for the second time, after doing it the first time.

### ISSUE THREAD

**Issue by bigplayer-ai** [guyzyl/whatsapp-contact-sync#89]
[Bug Report] Whatsapp contact sync does not work for the second time, after doing it the first time.
I want to resync my contacts profiles pitcures, whatsapp contact sync does not work for the second time after doing it for the first time.
I would defentily buy/purchase an application on my iPhone that does this(one time purchase only and not a subscription).

**Comment by guyzyl** [comment]
Can you give more context into what you mean by "not working"? 
Are you not able to connect WhatsApp? Is it not syncing anything?

**Comment by bigplayer-ai** [comment]
> Can you give more context into what you mean by "not working"? Are you not able to connect WhatsApp? Is it not syncing anything?
> 
> Also, I'm glad to hear you'd be open to buy an iPhone app for this, but this is not something I'm currently planning. In the meantime, you're more than welcome to buy me coffee [here](https://www.buymeacoffee.com/guyzyl) :)

Sorry for being unclear,
After scanning the WhatsApp code, The page died not redirect to google photos

**Comment by bigplayer-ai** [comment]
> That indeed sounds like a bug. Can you try to do that again and note the time you're trying to authenticate? That way I can check the logs for errors for your specific session. Also, try to see if the any errors appear in the console please.

Okay, Right now I don't need to resync my contacts photso, I will do that later on.
Please consider an iPhone application, you would make a good money from it lol:)

**Comment by guyzyl** [comment]
Sure, I'll think about it 😄
