### ISSUE TITLE
Higher Picture Quality for photo sync?

### ISSUE THREAD

**Issue by bigplayer-ai** [guyzyl/whatsapp-contact-sync#90]
Hey,
After viewing the contacts' they tend to be blurry, Can you add the option for higher picture quality download from whatsapp?

**Comment by guyzyl** [comment]
There is no such option since there isn't an option to control the photos resolution when downloading it using `whatsapp-web.js`.
Also, I think it's safe to assume that WhatsApp isn't storing (or at least serving them) in a very high resolution.

I'm guessing that the photos are blurry since they're blurry in peoples profiles.
If you have concrete examples of photos that are sharp in the profile but get uploaded blurry, I'd be glad to look it over again :)

**Comment by bigplayer-ai** [comment]
> There is no such option since there isn't an option to control the photos resolution when downloading it using `whatsapp-web.js`. Also, I think it's safe to assume that WhatsApp isn't storing (or at least serving them) in a very high resolution.
> 
> I'm guessing that the photos are blurry since they're blurry in peoples profiles. If you have concrete examples of photos that are sharp in the profile but get uploaded blurry, I'd be glad to look it over again :)

They are not blurry in WhatsApp, only in m in google photos
For example these two  photos
On WhatsApp:
![Screenshot 2023-04-03 at 10 52 43](https://user-images.githubusercontent.com/119108387/229446092-74590e07-333e-430b-883e-aae5f5c93a4a.png)
On google photos:
![17CD93E5-E2E4-430B-82CA-66FC7315DE67](https://user-images.githubusercontent.com/119108387/229446207-742797ba-25a5-40d7-8406-5ec8b4dc93ec.png)

**Comment by guyzyl** [comment]
The original photos doesn't seem very sharp, but the one uploaded to Google contacts looks even worse.
I'll try to see if there's some downscaling happening anywhere during the process, but it will take me a while to get around to it.

**Comment by bigplayer-ai** [comment]
> The original photos doesn't seem very sharp, but the one uploaded to Google contacts looks even worse. I'll try to see if there's some downscaling happening anywhere during the process, but it will take me a while to get around to it.

Oh this is because it's a screenshot, I have other contacts that have sharper contacts photos.

**Comment by whyrnld** [comment]
Same thing happens to me

**Comment by guyzyl** [comment]
I have not noticed this behavior when syncing my contacts. Can anyone try to pinpoint the bug causing this?

**Comment by alequisgomes** [comment]
Hi everyone,
I was having this same issue when trying to view some of the pictures in my samsung contacts app, but when accessing the google contacts via web (contacts.google.com), the pictures seemed to have a reasonable resolution, which indicates the incorrect sync could be in the interface between google contacts and the phone app.

For anyone else having this issue, i recommend accessing contacts.google.com and checking if the pictures are also super blurry there.

This app is great and did exactly what I needed. Thanks for that.

**Comment by guyzyl** [comment]
@alequisgomes thanks for the update!
@bigplayer-ai / @whyrnld can you confirm this?

**Comment by seemebreakthis** [comment]
> @alequisgomes thanks for the update! @bigplayer-ai / @whyrnld can you confirm this?

Can confirm with my Xiaomi Mi 11 phone.  Downloaded the google contacts app, opened a specific contact, and the blurry picture was instantly updated in my samsung contacts app... 

Which means I need to do this one by one.  But it seems the high-res picture are already at Google's side, it just doesn't get updated properly unless you 'refresh' each one in the contacts app first.

**Comment by bigplayer-ai** [comment]
> @alequisgomes thanks for the update! @bigplayer-ai / @whyrnld can you confirm this?

I can not confirm, I have the blurry/very low resolution/pixelated contact picture in Google Contacts application and Google Contacts Web. On WhatsApp the contact profile picture seems very clear and sharp on web and on application!

**Comment by guyzyl** [comment]
@bigplayer-ai what happens if you right click on the picture in GContacts web, and open picture in a new tab? I suspect the picture might have only partially loaded, but opening in a new tab should load the full-res picture.

If it's still blurry, can you help me find a way to replicate the issue?

**Comment by bigplayer-ai** [comment]
I think the problem is that WhatsApp only partially loads profile pictures for contacts not directly messaged. Is there a way to fully load all pictures of all contacts in WhatsApp before downloading them?Google Contacts' profile pictures are also partially loaded even in new tabs or when zoomed. I am using web google contacts and application on my phone The issue specifically involves WhatsApp partially loading pictures for some contacts, not all.On 17 Jan 2024, at 10:39, Guy Zylberberg ***@***.***> wrote:﻿
@bigplayer-ai what happens if you right click on the picture in GContacts web, and open picture in a new tab? I suspect the picture might have only partially loaded, but opening in a new tab should load the full-res picture.
If it's still blurry, can you help me find a way to replicate the issue?

**Comment by guyzyl** [comment]
That might be what's happening, but I have no way of controlling it.
The only thing I do to download the profile picture from WhatsApp is use [this](https://docs.wwebjs.dev/Client.html#getProfilePicUrl) API call which gives me the pictures URL, and then [download](https://docs.wwebjs.dev/MessageMedia.html#.fromUrl) it.

**Comment by PROxZIMA** [comment]
This issue is completely related to data syncing between the Google Phone app and the Google Contacts app. This application is properly setting the high quality image which is coming from WhatsApp.

I too was confused at first but after opening the contact photos in the Google Contacts app, the contact photo got updated in the Google Phone app too.

This issue can be closed.

**Comment by guyzyl** [comment]
Thanks for the update, I'l go ahead and close the issue :)
