### ISSUE TITLE
[Feature Request] Logout from WhatsApp after syncing photos from WhatsApp to Google Contacts.

### ISSUE THREAD

**Issue by bigplayer-ai** [guyzyl/whatsapp-contact-sync#93]
[Feature Request] Logout from WhatsApp after syncing photos from WhatsApp to Google Contacts.

**Comment by guyzyl** [comment]
That's a great idea, but it's not possible from the server side.
I'm already destroying the session and delete it on the server side, but you still need to remove the authentication from the WhatsApp app on you phone (which I can't trigger from the server).

**Comment by bigplayer-ai** [comment]
is this repo still active?

**Comment by guyzyl** [comment]
Yes, but this is a side project of mine. Unless there are critical bugs, it will take me some time to get around to developing new features.

This is an open source project, contributions are always welcome 😁.

**Comment by guyzyl** [comment]
I just tried testing the `lougout()` function but it doesn't seem to actually log out, it doesn't remove the device from the linked devices list.

**Comment by guyzyl** [comment]
Apparently improvements to the `logout()` mechanism have been made in [v1.22.1](https://github.com/pedroslopez/whatsapp-web.js/releases/tag/v1.22.1), need to test again and see if it works now.

**Comment by guyzyl** [comment]
Tested again, still nothing
