### ISSUE TITLE
QR doesn't appear on first load if container was just launched

### ISSUE THREAD

**Issue by guyzyl** [guyzyl/whatsapp-contact-sync#94]
The website is currently hosted on GCP Run. That means that when no one is accessing the website the Docker container is taken down, and a new one is created when someone accesses the website.
In addition to that, the app is based whatsapp-api.js which uses a headless Chrome browser to function.

The combination of these two facts causes some sort of bug where after the container is launched, the QR isn't loaded and a reload to the page is required.

**Comment by guyzyl** [comment]
Can you try again and wait about 2 seconds? I just tried on whasync.com and it worked for me.
(If it doesn't comment here / email me and I'll send you a refund)

**Comment by hiagocosta** [comment]
After 30 minutes it worked!

Em qui., 28 de nov. de 2024, 17:41, Guy Zylberberg ***@***.***>
escreveu:

**Comment by guyzyl** [comment]
Glad to hear! and I apologize it took so long.
